### ISSUE TITLE
Jade 旧版协议不兼容报错

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [LeavesMC/Leaves#189]
### 服务端版本 LeavesMC Version

git-Leaves-"ec5a1fc" 1.20.4

### 预期的行为 Expected behavior

假人正常运行，后台无报错

### 观测到的实际行为 Observed/Actual behavior

假人正常运行，但是后台狂刷报错
[假人报错.txt](https://github.com/LeavesMC/Leaves/files/14382471/default.txt)

### 复现步骤 Steps/models to reproduce

就是莫名报错，原因找不到

### 插件与数据包列表。 Plugin and Datapack List.

Plugins (37): AntiPopup, BottledExp, ChestSort, CMI, CMILib, ComfyWhitelist, ConditionalEvents, CoreProtect, FastAsyncWorldEdit, ForceResourcepacks, GSit, InvSeePlusPlus, Ip2region, ItemEdit, ItemTag, JukeBox, LiteBans, LogFilter, LuckPerms, Matrix, NekoTraps, NoteBlockAPI, PlaceholderAPI, PlugManX, ProtocolLib, RayTraceAntiXray, ReviveMe, SelectionVisualizer, SkinsRestorer, spark, TAB, TabTPS, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, Vulcan

### 更多详细信息。 The more information.

在build183版本时无任何报错

**Comment by s-yh-china** [comment]
不是假人的问题 是jade协议 如果玩家用了旧版本jade就会这样
可以先把jade关了 或者让玩家都升级jade到最新版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 更新build185版本后，假人后台报错 (Issue #189)




 
服务端版本 LeavesMC Version
 
git-Leaves-"ec5a1fc" 1.20.4
 
预期的行为 Expected behavior
 
假人正常运行，后台无报错
 
观测到的实际行为 Observed/Actual behavior
 
假人正常运行，但是后台狂刷报错
 假人报错.txt
 
复现步骤 Steps/models to reproduce
 
就是莫名报错，原因找不到
 
插件与数据包列表。 Plugin and Datapack List.
 
Plugins (37): AntiPopup, BottledExp, ChestSort, CMI, CMILib, ComfyWhitelist, ConditionalEvents, CoreProtect, FastAsyncWorldEdit, ForceResourcepacks, GSit, InvSeePlusPlus, Ip2region, ItemEdit, ItemTag, JukeBox, LiteBans, LogFilter, LuckPerms, Matrix, NekoTraps, NoteBlockAPI, PlaceholderAPI, PlugManX, ProtocolLib, RayTraceAntiXray, ReviveMe, SelectionVisualizer, SkinsRestorer, spark, TAB, TabTPS, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, Vulcan
 
更多详细信息。 The more information.
 
在build183版本时无任何报错

**Comment by s-yh-china** [comment]
emmmmmm，坏了()
建议让玩家升级下jade版本吧 或者暂时回退一下版本
等我看看怎么修复这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 下午3:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 更新build185版本后，假人后台报错 (Issue #189)




 
诶，可是我jade-protocol: false本来就是关的呀
