### ISSUE TITLE
在使用命名的物品杀死玩家后，死亡信息中无法预览物品属性

### ISSUE THREAD

**Issue by odyy345-u** [LeavesMC/Leaves#296]
### 服务端版本 LeavesMC Version

1.21-39-master@a7b7a1a

### 预期的行为 Expected behavior

聊天栏死亡信息中可以正确预览物品信息

### 观测到的实际行为 Observed/Actual behavior

在使用被命名的物品杀死玩家或已命名的生物后，显示的死亡信息后没有显示物品属性

### 复现步骤 Steps/models to reproduce

1.使用被命名且有附魔等信息的物品杀点什么（只要能产生死亡信息即可）
![fig2](https://github.com/user-attachments/assets/e48cb676-e43f-46a2-bb69-7757778ca1a6)
2.查看死亡信息里的物品名称
![fig1](https://github.com/user-attachments/assets/01cae9d3-f289-4957-b3e4-8e224b681993)

### 插件与数据包列表。 Plugin and Datapack List.

[Server] [18:39:37 INFO]: Server Plugins (14):
[Server] [18:39:37 INFO]: Bukkit Plugins:
[Server] [18:39:37 INFO]:  - AuthMe, CoreProtect, dynmap, Essentials, LuckPerms, MiniMOTD, Multiverse-Core, PlaceholderAPI, *PotatoIdDisplay, SkinsRestorer
[Server] [18:39:37 INFO]:  ViaBackwards, ViaRewind, ViaVersion, WorldEdit

[Server] [18:40:03 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[Server] [18:40:03 INFO]: There are no more data packs available

**Comment by s-yh-china** [comment]
能否关闭所有插件先测试一下呢，我不太确定是否是插件引起的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 晚上6:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 在使用命名的物品杀死玩家后，死亡信息中无法预览物品属性 (Issue #296)




 
服务端版本 LeavesMC Version
 
***@***.***
 
预期的行为 Expected behavior
 
聊天栏死亡信息中可以正确预览物品信息
 
观测到的实际行为 Observed/Actual behavior
 
在使用被命名的物品杀死玩家或已命名的生物后，显示的死亡信息后没有显示物品属性
 
复现步骤 Steps/models to reproduce
 
1.使用被命名且有附魔等信息的物品杀点什么（只要能产生死亡信息即可）
 fig1.png (view on web)
 2.查看死亡信息里的物品名称
 fig1.png (view on web)
 
插件与数据包列表。 Plugin and Datapack List.
 
[Server] [18:39:37 INFO]: Server Plugins (14):
 [Server] [18:39:37 INFO]: Bukkit Plugins:
 [Server] [18:39:37 INFO]:  - AuthMe, CoreProtect, dynmap, Essentials, LuckPerms, MiniMOTD, Multiverse-Core, PlaceholderAPI, *PotatoIdDisplay, SkinsRestorer
 [Server] [18:39:37 INFO]:  ViaBackwards, ViaRewind, ViaVersion, WorldEdit
 
[Server] [18:40:03 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
 [Server] [18:40:03 INFO]: There are no more data packs available
 
更多详细信息。 The more information.
 
No response

**Comment by GLDYM** [comment]
一眼 Via 的问题，叉出去。1.21 哪来的 NBT。
